apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-app-backend
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: todo-app-backend
