apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-app-frontend
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: todo-app-frontend
