apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
  namespace: todo-app
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    secretKeyRef:
      name: kafka-creds
      key: brokers
  - name: authType
    value: "password"
  - name: saslUsername
    secretKeyRef:
      name: kafka-creds
      key: username
  - name: saslPassword
    secretKeyRef:
      name: kafka-creds
      key: password
  - name: consumerGroup
    value: "todo-app-group"
  - name: disableTls
    value: "false"
  - name: maxMessageBytes
    value: "1048576"
  - name: consumeRetryInterval
    value: "200ms"
